# Generated by Django 4.2 on 2026-01-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_body'),
        ('articles', '0002_alter_article_id'),
    ]

    operations = [
    ]
