# Generated by ChatGPT on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=800),
        ),
    ]
